dist: xenial
sudo: required
language: clojure
jdk:
- openjdk8
- openjdk9
- openjdk10
- openjdk11
- openjdk17
before_script:
- sudo add-apt-repository ppa:duggan/bats --yes
- sudo apt update -qq
- sudo apt-get install -qq coreutils bats
script:
- chmod 600 test/creds.*
- lein clj-kondo
- lein bin
- bats --tap test
deploy:
  provider: releases
  api_key:
    secure: "SrwN73z1Wxm4sNDw3BbHCucWvm/NZF0/5/r4MYQ5DgYNMwj3nUj9OAQP/swERvtE4SecAYROUnaDy2aaF3/R82tGp+5IvO+OvdrQlT1Cao6EUb4jKxtaxho8/qnjvPg06TY571ZbJenP4AJTgL5FM3Tu50Td0NmXqLCA7CXVJHmRSolE9I8iebXK1xu1WFVCDBTmtzwCBl1YAHDX/2YPpE5O1YCjhk/7+44PATx2pe3o9q+j8lEbBaj1mfW37s+HBFpR28z/PZWKQRXCJPkEjZIbn7S0mymNyOHoZyxzbG4AcPzqQ0g2xB62WngfAtjeiivEiNDDXHSpfnCGYSi4K9FME92DkbtWhv2NYuu7/0AlwE93XVFz9Xs94ocP/3ApkoEliXViH314PdhZkCBlE7otGEdsOprMa7CKTxoVy16uU70X8HSpJy8JchS8pTMZfQSrrR8ISFiEHesoeUVLNCPMciOvnbcMpcZkoJ4QeivjuHU9lAbst7H0IGgOvivlH70A6S1et67eDleBo9BCsyeJC1qAffwk8QKExGVB9WNEFxTsq2OYUuUSiApvKWKAvhMhZRrBm4uDnAAl9YDCXJja+ud93gaC+8DyJNT9p/45EhOEEOCafGFjt5pg6ku34CGUJJp+w+s+/e8wfopUuLyJhHRWaPpQS4w58IDgGHs="
  file_glob: true
  file:
    - target/default/jmx-dump
    - target/uberjar/*-standalone.jar
  skip_cleanup: true
  on:
    tags: true
    draft: true
    jdk: openjdk17
