---
dist: xenial
sudo: required
language: clojure
jdk:
  - openjdk6
  - openjdk8
  - openjdk9
  - openjdk12
  - oraclejdk6
  - oraclejdk8
  - oraclejdk9
  - oraclejdk12
before_script:
  - sudo add-apt-repository ppa:duggan/bats --yes
  - sudo apt update -qq
  - sudo apt-get install -qq coreutils bats
script:
  - chmod 600 test/creds.*
  - lein uberjar
  - bats --tap test
