---
dist: xenial
sudo: required
language: clojure
jdk:
  - openjdk8
  - openjdk9
  - openjdk10
  - openjdk11
  - openjdk12
  - openjdk13
  - openjdk14
before_script:
  - sudo add-apt-repository ppa:duggan/bats --yes
  - sudo apt update -qq
  - sudo apt-get install -qq coreutils bats
script:
  - chmod 600 test/creds.*
  - lein clj-kondo
  - lein bin
  - bats --tap test
