---
sudo: required
language: clojure
jdk:
  - openjdk8
  - openjdk12
  - oraclejdk8
  - oraclejdk12
before_script:
  - sudo add-apt-repository ppa:duggan/bats --yes
  - sudo apt update -qq
  - sudo apt-get install -qq coreutils bats
script:
  - chmod 600 test/creds.*
  - lein uberjar
  - bats --tap test
